# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zc702/zc702.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702 || ORIG_REF_NAME==zc702}]

# IP: bd/zc702/ip/zc702_processing_system7_1_0/zc702_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_processing_system7_1_0 || ORIG_REF_NAME==zc702_processing_system7_1_0}]

# IP: bd/zc702/ip/zc702_xlconcat_1_0/zc702_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_xlconcat_1_0 || ORIG_REF_NAME==zc702_xlconcat_1_0}]

# IP: bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_1_0 || ORIG_REF_NAME==zc702_proc_sys_reset_1_0}]

# IP: bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_2_1 || ORIG_REF_NAME==zc702_proc_sys_reset_2_1}]

# IP: bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_3_2 || ORIG_REF_NAME==zc702_proc_sys_reset_3_2}]

# IP: bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_4_3 || ORIG_REF_NAME==zc702_proc_sys_reset_4_3}]

# IP: bd/zc702/ip/zc702_get_0_0/zc702_get_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_get_0_0 || ORIG_REF_NAME==zc702_get_0_0}]

# IP: bd/zc702/ip/zc702_set_0_0/zc702_set_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_set_0_0 || ORIG_REF_NAME==zc702_set_0_0}]

# IP: bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_get_0_if_0 || ORIG_REF_NAME==zc702_get_0_if_0}]

# IP: bd/zc702/ip/zc702_get_0_val_r_0/zc702_get_0_val_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_get_0_val_r_0 || ORIG_REF_NAME==zc702_get_0_val_r_0}]

# IP: bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_set_0_if_0 || ORIG_REF_NAME==zc702_set_0_if_0}]

# IP: bd/zc702/ip/zc702_axi_ic_ps7_M_AXI_GP0_0/zc702_axi_ic_ps7_M_AXI_GP0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_axi_ic_ps7_M_AXI_GP0_0 || ORIG_REF_NAME==zc702_axi_ic_ps7_M_AXI_GP0_0}]

# IP: bd/zc702/ip/zc702_xbar_0/zc702_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_xbar_0 || ORIG_REF_NAME==zc702_xbar_0}]

# IP: bd/zc702/ip/zc702_axi_ic_ps7_S_AXI_ACP_0/zc702_axi_ic_ps7_S_AXI_ACP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_axi_ic_ps7_S_AXI_ACP_0 || ORIG_REF_NAME==zc702_axi_ic_ps7_S_AXI_ACP_0}]

# IP: bd/zc702/ip/zc702_xbar_1/zc702_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_xbar_1 || ORIG_REF_NAME==zc702_xbar_1}]

# IP: bd/zc702/ip/zc702_ps7_irq_const_0/zc702_ps7_irq_const_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_ps7_irq_const_0 || ORIG_REF_NAME==zc702_ps7_irq_const_0}]

# IP: bd/zc702/ip/zc702_acp_axcache_0xF_0/zc702_acp_axcache_0xF_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_acp_axcache_0xF_0 || ORIG_REF_NAME==zc702_acp_axcache_0xF_0}]

# IP: bd/zc702/ip/zc702_s00_regslice_0/zc702_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_s00_regslice_0 || ORIG_REF_NAME==zc702_s00_regslice_0}]

# IP: bd/zc702/ip/zc702_s00_data_fifo_0/zc702_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_s00_data_fifo_0 || ORIG_REF_NAME==zc702_s00_data_fifo_0}]

# IP: bd/zc702/ip/zc702_m00_regslice_0/zc702_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_m00_regslice_0 || ORIG_REF_NAME==zc702_m00_regslice_0}]

# IP: bd/zc702/ip/zc702_m01_regslice_0/zc702_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_m01_regslice_0 || ORIG_REF_NAME==zc702_m01_regslice_0}]

# IP: bd/zc702/ip/zc702_s00_regslice_1/zc702_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_s00_regslice_1 || ORIG_REF_NAME==zc702_s00_regslice_1}]

# IP: bd/zc702/ip/zc702_s01_regslice_0/zc702_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_s01_regslice_0 || ORIG_REF_NAME==zc702_s01_regslice_0}]

# IP: bd/zc702/ip/zc702_m00_data_fifo_0/zc702_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_m00_data_fifo_0 || ORIG_REF_NAME==zc702_m00_data_fifo_0}]

# IP: bd/zc702/ip/zc702_m00_regslice_1/zc702_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_m00_regslice_1 || ORIG_REF_NAME==zc702_m00_regslice_1}]

# IP: bd/zc702/ip/zc702_auto_pc_0/zc702_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_auto_pc_0 || ORIG_REF_NAME==zc702_auto_pc_0}]

# IP: bd/zc702/ip/zc702_auto_pc_1/zc702_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_auto_pc_1 || ORIG_REF_NAME==zc702_auto_pc_1}]

# IP: bd/zc702/ip/zc702_auto_us_df_0/zc702_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_auto_us_df_0 || ORIG_REF_NAME==zc702_auto_us_df_0}]

# IP: bd/zc702/ip/zc702_auto_us_df_1/zc702_auto_us_df_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_auto_us_df_1 || ORIG_REF_NAME==zc702_auto_us_df_1}]

# XDC: bd/zc702/ip/zc702_processing_system7_1_0/zc702_processing_system7_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_processing_system7_1_0 || ORIG_REF_NAME==zc702_processing_system7_1_0}] {/inst }]/inst ]]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_1_0 || ORIG_REF_NAME==zc702_proc_sys_reset_1_0}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_1_0 || ORIG_REF_NAME==zc702_proc_sys_reset_1_0}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_2_1 || ORIG_REF_NAME==zc702_proc_sys_reset_2_1}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_2_1 || ORIG_REF_NAME==zc702_proc_sys_reset_2_1}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_3_2 || ORIG_REF_NAME==zc702_proc_sys_reset_3_2}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_3_2 || ORIG_REF_NAME==zc702_proc_sys_reset_3_2}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2_ooc.xdc

# XDC: bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_4_3 || ORIG_REF_NAME==zc702_proc_sys_reset_4_3}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zc702_proc_sys_reset_4_3 || ORIG_REF_NAME==zc702_proc_sys_reset_4_3}]

# XDC: bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3_ooc.xdc

# XDC: bd/zc702/ip/zc702_get_0_0/constraints/get_ooc.xdc

# XDC: bd/zc702/ip/zc702_set_0_0/constraints/set_ooc.xdc

# XDC: bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_xdc_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_get_0_if_0 || ORIG_REF_NAME==zc702_get_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_xdc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_get_0_if_0 || ORIG_REF_NAME==zc702_get_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_xdc_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_set_0_if_0 || ORIG_REF_NAME==zc702_set_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_xdc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_set_0_if_0 || ORIG_REF_NAME==zc702_set_0_if_0}] {/U0 }]/U0 ]]

# XDC: bd/zc702/ip/zc702_xbar_0/zc702_xbar_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_xbar_1/zc702_xbar_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_s00_regslice_0/zc702_s00_regslice_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_s00_data_fifo_0/zc702_s00_data_fifo_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_m00_regslice_0/zc702_m00_regslice_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_m01_regslice_0/zc702_m01_regslice_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_s00_regslice_1/zc702_s00_regslice_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_s01_regslice_0/zc702_s01_regslice_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_m00_data_fifo_0/zc702_m00_data_fifo_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_m00_regslice_1/zc702_m00_regslice_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_auto_pc_0/zc702_auto_pc_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_auto_pc_1/zc702_auto_pc_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_auto_us_df_0/zc702_auto_us_df_0_ooc.xdc

# XDC: bd/zc702/ip/zc702_auto_us_df_0/zc702_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_auto_us_df_0 || ORIG_REF_NAME==zc702_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/zc702/ip/zc702_auto_us_df_1/zc702_auto_us_df_1_ooc.xdc

# XDC: bd/zc702/ip/zc702_auto_us_df_1/zc702_auto_us_df_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zc702_auto_us_df_1 || ORIG_REF_NAME==zc702_auto_us_df_1}] {/inst }]/inst ]]

# XDC: bd/zc702/zc702_ooc.xdc
