# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.cache/wt [current_project]
set_property parent.project_path C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:0.9 [current_project]
set_property ip_repo_paths {
  c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/iprepo/repo
  c:/Xilinx/SDSoC/2015.4/data/ip/xilinx
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/zc702.bd
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_processing_system7_1_0/zc702_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_1_0/zc702_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_2_1/zc702_proc_sys_reset_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_3_2/zc702_proc_sys_reset_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_proc_sys_reset_4_3/zc702_proc_sys_reset_4_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_get_0_0/constraints/get_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_set_0_0/constraints/set_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_xdc_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_get_0_if_0/zc702_get_0_if_0_xdc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_xdc_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_set_0_if_0/zc702_set_0_if_0_xdc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_xbar_0/zc702_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_xbar_1/zc702_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_s00_regslice_0/zc702_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_s00_data_fifo_0/zc702_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_m00_regslice_0/zc702_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_m01_regslice_0/zc702_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_s00_regslice_1/zc702_s00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_s01_regslice_0/zc702_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_m00_data_fifo_0/zc702_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_m00_regslice_1/zc702_m00_regslice_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_pc_0/zc702_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_pc_1/zc702_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_us_df_0/zc702_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_us_df_0/zc702_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_us_df_1/zc702_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/ip/zc702_auto_us_df_1/zc702_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/zc702_ooc.xdc]
set_property is_locked true [get_files C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/bd/zc702/zc702.bd]

read_verilog -library xil_defaultlib C:/Users/sskalick/Xilinx/hash/hash/SDDebug/_sds/p0/ipi/zc702.srcs/sources_1/imports/hdl/zc702_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top zc702_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef zc702_wrapper.dcp
catch { report_utilization -file zc702_wrapper_utilization_synth.rpt -pb zc702_wrapper_utilization_synth.pb }
